SEED = 456321

SIZE = 50
CAPACITY = 40
NUMBER_OF_DEPOTS = 1

NUMBER_OF_INSTANCES = 1

ITERATIONS = 3000
WEIGHTS = [1, 1, 1, 1]
OPERATOR_DECAY = 0.8
COLLECT_STATISTICS = True

DEGREE_OF_DESTRUCTION = 0.25
DETERMINISM = 6

FILE_NAME = "{0}inst_{1}nod_{2}cap_{3}dep_{4}iter_{5}decay_{6}destr_{7}determ.pickle"\
            .format(NUMBER_OF_INSTANCES, SIZE, CAPACITY, NUMBER_OF_DEPOTS,
                    ITERATIONS, OPERATOR_DECAY, DEGREE_OF_DESTRUCTION, DETERMINISM)
FILE_MODE = 'wb'
