import os

DATASET_PREFIX = 'inputs_mask_labels_'
STATISTICS_DATA_PATH = os.getcwd().rpartition('/')[0] + '/data/'
ALNS_STATISTICS_FILE = 'dataset_50-50_1inst_50nod_40cap_1dep_50000iter_0.8decay_0.35destr_18determ.pickle'
DATASET_PATH = STATISTICS_DATA_PATH + DATASET_PREFIX + ALNS_STATISTICS_FILE
MODEL_PARAMETERS_PATH = STATISTICS_DATA_PATH + 'parametersGCN'

HIDDEN_NODE_DIMENSIONS = [64, 32, 32, 32]
HIDDEN_EDGE_DIMENSIONS = [32, 16, 16, 8]
HIDDEN_LINEAR_DIMENSION = 32
OUTPUT_SIZE = 3
DROPOUT_PROBABILITY = 0.2
MAX_EPOCH = 5000
EPSILON = 1e-5

INITIAL_LEARNING_RATE = 0.00001
LEARNING_RATE_DECREASE_FACTOR = 0.9

MASK_SEED = 123456
