from project_root_path import get_project_root_path

SEED = 456322

SIZE = 19
CAPACITY = 14
NUMBER_OF_DEPOTS = 1

NUMBER_OF_INSTANCES = 2000

ITERATIONS = 30
WEIGHTS = [1, 1, 1, 1]
OPERATOR_DECAY = 0.8
COLLECT_STATISTICS = True

DEGREE_OF_DESTRUCTION = 0.35
DETERMINISM = 18

ACCEPT_NODES_RANDOMLY = 0.1

START_TEMPERATURE_CONTROL = 0.05
COOLING_RATE = 0.99995
END_TEMPERATURE = 0.01

ROOT_PATH = get_project_root_path()
FILE_PATH = ROOT_PATH \
            + "/data/"\
            + "stats_{0}it{1}in.pickle".format(ITERATIONS, NUMBER_OF_INSTANCES)
FILE_MODE = 'wb'
